package zti.backend.model;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDate;
import java.util.List;

/**
 * Entity representing a single day of the festival.
 * <p>
 * This class maps to the {@code days} table in the {@code mfkip} schema.
 * It stores basic information about a festival day, including its name, calendar date,
 * and a flag indicating whether it is the currently active day in the system.
 * </p>
 * <p>
 * Note: The use of Lombok's {@code @Data} annotation automatically generates
 * boilerplate code at compile time, including getters, setters, {@code equals()},
 * {@code hashCode()}, and a {@code toString()} method.
 * </p>
 */
@Entity
@Table(name = "days", schema = "mfkip")
@Data
public class Day {

    /**
     * The unique identifier for the day.
     * Auto-generated by the underlying database (Identity strategy).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The descriptive name of the day (e.g., "Czwartek", "Dzień 1").
     * This field is mandatory and cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The specific calendar date of this festival day.
     */
    private LocalDate date;

    /**
     * A flag indicating if this day is the currently active one.
     * Maps to the {@code is_active} column in the database.
     * Defaults to {@code false}. Only one day should typically be active at a time.
     */
    @Column(name = "is_active")
    private boolean isActive = false;

}