package zti.backend.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalTime;

/**
 * Entity representing a single scheduled performance or break within the festival.
 * <p>
 * This class maps to the {@code performances} table in the {@code mfkip} schema.
 * It tracks scheduling information (planned, changed, and actual times), the name
 * of the performing group, current stage status, and the assigned volunteer.
 * </p>
 * <p>
 * Note: The use of Lombok's {@code @Data} annotation automatically generates
 * boilerplate code at compile time, including getters, setters, {@code equals()},
 * {@code hashCode()}, and a {@code toString()} method.
 * </p>
 */
@Entity
@Table(name = "performances", schema = "mfkip")
@Data
@NoArgsConstructor
public class Performance {

    /**
     * The unique identifier for the performance.
     * Auto-generated by the underlying database (Identity strategy).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The specific festival day this performance belongs to.
     * <p>
     * Eagerly fetched to ensure day details are available immediately.
     * {@link JsonIgnoreProperties} prevents infinite recursion during JSON serialization.
     * </p>
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "day_id", nullable = false)
    @JsonIgnoreProperties("performances")
    private Day day;

    /**
     * The originally planned start time of the performance according to the official schedule.
     * Formatted as "HH:mm:ss" in JSON payloads.
     */
    @Column(name = "planned_start_time", nullable = false)
    @JsonFormat(pattern = "HH:mm:ss")
    private LocalTime plannedStartTime;

    /**
     * An updated start time, used if the schedule shifts dynamically or items are reordered.
     * If present, this typically overrides the planned start time in the view.
     */
    @Column(name = "changed_start_time")
    private LocalTime changedStartTime;

    /**
     * The timestamp when the performance actually went live on stage.
     */
    @Column(name = "actual_start_time")
    private LocalTime actualStartTime;

    /**
     * The timestamp when the performance finished.
     */
    @Column(name = "end_time")
    private LocalTime endTime;

    /**
     * The name of the performer, ensemble, or choir.
     */
    @Column(name = "performer_name", nullable = false)
    private String performerName;

    /**
     * The current lifecycle status of the performance on stage.
     * Defaults to "none". Common values might include "ongoing", "finished", etc.
     */
    private String status = "none";

    /**
     * The volunteer assigned to look after or guide this specific performer/group.
     * Eagerly fetched to display assistant info in real-time views.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "volunteer_id")
    private Volunteer volunteer;

    /**
     * A flag indicating whether this row represents an actual performance or a scheduled technical break/intermission.
     * Maps to the {@code is_break} column and is serialized explicitly as {@code isBreak} in JSON.
     */
    @Column(name = "is_break")
    @JsonProperty("isBreak")
    private boolean isBreak = false;

}