package zti.backend.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity representing a festival volunteer.
 * <p>
 * This class maps to the {@code volunteers} table in the {@code mfkip} schema.
 * It stores contact and identification details for individuals who assist
 * performers, manage stage logistics, and help organize the event.
 * </p>
 * <p>
 * Note: The use of Lombok's {@code @Data} annotation automatically generates
 * boilerplate code at compile time, including getters, setters, {@code equals()},
 * {@code hashCode()}, and a {@code toString()} method.
 * </p>
 */
@Entity
@Table(name = "volunteers", schema = "mfkip")
@Data
public class Volunteer {

    /**
     * The unique identifier for the volunteer.
     * Auto-generated by the underlying database using the Identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The full name of the volunteer.
     * This field is mandatory and cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The contact phone number of the volunteer.
     * <p>
     * Used by reception, stage managers, or administrators for quick
     * communication during the festival.
     * </p>
     */
    private String phone;

}