spring.application.name=backend
server.port=8081

#ssh -L 5433:localhost:5432 2gwiozdzik@taurus
spring.datasource.url=jdbc:postgresql://localhost:5433/u2gwiozdzik?ssl=false&sslmode=disable&allowEncodingChanges=true
spring.datasource.username=u2gwiozdzik
spring.datasource.password=2gwiozdzik
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none