package zti.backend.dto;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for the {@link StatusUpdateRequest} Data Transfer Object (DTO).
 * <p>
 * This test suite verifies that Lombok's {@code @Data} annotation correctly
 * generates the required boilerplate methods, including getters, setters,
 * equals, hashCode, and toString mechanisms.
 * </p>
 */
class StatusUpdateRequestTest {

    /**
     * Tests the getter and setter methods generated by Lombok.
     */
    @Test
    void shouldSetAndGetStatus() {
        // Given
        StatusUpdateRequest request = new StatusUpdateRequest();
        String expectedStatus = "ongoing";

        // When
        request.setStatus(expectedStatus);

        // Then
        assertEquals(expectedStatus, request.getStatus(), "The getter should return the status that was set");
    }

    /**
     * Tests the equals() and hashCode() methods generated by Lombok.
     * <p>
     * Ensures that two different instances with the identical state (status)
     * are logically considered equal and produce the same hash code.
     * </p>
     */
    @Test
    void shouldVerifyEqualsAndHashCode() {
        // Given
        StatusUpdateRequest request1 = new StatusUpdateRequest();
        request1.setStatus("completed");

        StatusUpdateRequest request2 = new StatusUpdateRequest();
        request2.setStatus("completed");

        StatusUpdateRequest request3 = new StatusUpdateRequest();
        request3.setStatus("pending");

        // Then
        assertEquals(request1, request2, "Objects with the exact same status should be equal");
        assertEquals(request1.hashCode(), request2.hashCode(), "Objects with the exact same status should have the same hash code");
        assertNotEquals(request1, request3, "Objects with different statuses should not be equal");
    }

    /**
     * Tests the toString() method generated by Lombok.
     */
    @Test
    void shouldVerifyToString() {
        // Given
        StatusUpdateRequest request = new StatusUpdateRequest();
        request.setStatus("active");

        // When
        String toStringResult = request.toString();

        // Then
        assertTrue(toStringResult.contains("active"), "The toString method should contain the actual status value");
        assertTrue(toStringResult.contains("StatusUpdateRequest"), "The toString method should contain the class name");
    }
}